sim:
  fps: 30 # int
  render_realtime: True # boolean
  observation_space_format: classes # "rgb" or "classes"
  real_world_env: 'autosys' # optional: Used only when using tinycarlo-realworld to identify implementation
car:
  wheelbase: 0.0487 # m
  track_width: 0.027 # m
  max_velocity: 0.15 # m/s
  max_steering_angle: 30 # deg
  steering_speed: 30 # deg/s
  max_acceleration: 0.1 # m/s^2
  max_deceleration: 1.0 # m/s^2
  tinycar_hostname: '192.168.84.63' # example of autosys real world env specific param. Will be ignored if using standard tinycarlo
camera:
  position: [0.02,-0.01,0.022] # [x,y,z] in m relative to middle of front axle (x: forward, y: right, z: up)
  orientation: [25,0,0] # [pitch,roll,yaw] in degrees
  resolution: [128,160] # [height, width] in px
  fov: 120 # in degrees
  max_range: 0.5 # in m (can be None for infinite range)
  line_thickness: 2 # in px
map:
  json_path: ./maps/simple_layout.json # path to map file
  pixel_per_meter: 450
  spawn_points: [57, 143, 112, 121, 138, 157, 67, 46, 165, 124, 79, 33, 84, 21, 178, 7] # list of spawn points/ node indices (use examples/render_map.py to visualize the map and get the node indices)
